export const AuthWelcomeView = {
  AUTH_LOGIN: 0,
  AUTH_SIGNUP: 1,
  AUTH_FORGOT_PASSWORD: 2,
  AUTH_WELCOME: 3,
};

export const ForgotPasswordView = {
  FORGOT_PASSWORD: 0,
  PASSWORD_RECOVERY_CONFIRMATION: 1,
  PASSWORD_RECOVERY_SUCCESS: 3,
  RESET_LINK_CONFIRMATIONS: 4,
  RESET_LINK_RECOVERY_SUCCESS: 5,
  WELCOME: 6,
};

export const ORIENTATION = {
  PORTRAIT: 'PORTRAIT',
  LANDSCAPE: 'LANDSCAPE',
};